### ISSUE TITLE
camera preview issues on lower end phones

### ISSUE THREAD

**Issue by GeorvityLabs** [SunnyGrocery/ncnn-android-yolov4-tiny-custom#1]
Hi @SunnyGrocery ,

This is an amazing project!
It's working fine on my 4gb ram phone , but on my 1gb ram device with 1.3ghz cpu , it is having some issues.
Green lines are appearing on the imageview instead of the proper camera preview.
Hope you could suggest a fix, to get a proper camera preview output on the imageview.

I've attached a screenshot of the issue with the camera preview.

![Screenshot from 2021-06-24 14-09-13](https://user-images.githubusercontent.com/58555432/123231697-0ff9bb00-d4f6-11eb-94c9-2a7d4e5a0787.png)

**Comment by SunnyGrocery** [comment]
Try to reduce the size to 240*240 in [code1](https://github.com/SunnyGrocery/ncnn-android-yolov4-tiny-custom/blob/473492fe4538d205b0ae655ad982ec14c1febb84/app/src/main/java/top/sun1999/MainActivity.java#L112) and [code2](https://github.com/SunnyGrocery/ncnn-android-yolov4-tiny-custom/blob/473492fe4538d205b0ae655ad982ec14c1febb84/app/src/main/java/top/sun1999/MainActivity.java#L125), if the app still can`t  work well, you can try to use larger ram phone.....
