### ISSUE TITLE
what is the performance of the yolov4-tiny mask/nomask detection on darknet?

### ISSUE THREAD

**Issue by liminghu** [SunnyGrocery/ncnn-android-yolov4-tiny-custom#2]
Just curious, what is the performance of the yolov4-tiny mask/nomask detection on darknet?

**Comment by SunnyGrocery** [comment]
That table shows the performance of the yolov4-tiny mask/nomask detection on darknet:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/SUNNYG~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/SUNNYG~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/SUNNYG~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">





</head>

<body lang=ZH-CN style='tab-interval:21.0pt;text-justify-trim:punctuation'>


<div align=center>



AP of nomask | AP of masked | mAP | Recall | Average IoU | TP | FP | FN
-- | -- | -- | -- | -- | -- | -- | --
73.93% | 94.53% | 84.23 % | 80% | 62.73 % | 3895 | 938 | 971



</div>


</body>

</html>

**Comment by liminghu** [comment]
@SunnyGrocery thanks for the information. it seems to me there is still room to get better performance, you can try:
https://github.com/Megvii-BaseDetection/YOLOX

**Comment by SunnyGrocery** [comment]
OK, but I haven`t enough time to optimize the project now. thanks for your advice. And also thanks for your suggestions so much ~
